version: '3'

services:
  node-server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - PORT=3001
    depends_on:
      - ml-service
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
      
  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
      - /app/venv
    environment:
      - LOG_LEVEL=INFO
